<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="theme" content="hugo-academic">
  <meta name="generator" content="Hugo 0.19" />
  <meta name="author" content="Zheng Si">
  <meta name="description" content="Second year Matsers student in Biostatistics">

  
  
  
  
    
    
    <link rel="stylesheet" href="/css/highlight.min.css">
    
  
  <link rel="stylesheet" href="/css/bootstrap.min.css">
  <link rel="stylesheet" href="/css/font-awesome.min.css">
  <link rel="stylesheet" href="/css/academicons.min.css">
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato:400,700|Merriweather|Roboto+Mono">
  <link rel="stylesheet" href="/css/hugo-academic.css">
  

  <link rel="alternate" href="https://zsi1.github.io/index.xml" type="application/rss+xml" title="Zheng Si, Mac">
  <link rel="feed" href="https://zsi1.github.io/index.xml" type="application/rss+xml" title="Zheng Si, Mac">

  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/apple-touch-icon.png">

  <link rel="canonical" href="https://zsi1.github.io/post/march-13-2017-pre-class/">

  

  <title>March-13-2017-Pre-Class | Zheng Si, Mac</title>

</head>
<body id="top" data-spy="scroll" data-target="#navbar-main" data-offset="71">

<nav class="navbar navbar-default navbar-fixed-top" id="navbar-main">
  <div class="container">

    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Zheng Si, Mac</a>
    </div>

    
    <div class="collapse navbar-collapse">

      
      <ul class="nav navbar-nav navbar-right">
        

        

        <li class="nav-item">
          <a href="/#about">
            
            <span>Home</span>
          </a>
        </li>

        
        

        

        <li class="nav-item">
          <a href="/#posts">
            
            <span>Posts</span>
          </a>
        </li>

        
        

        

        <li class="nav-item">
          <a href="/#projects">
            
            <span>Projects</span>
          </a>
        </li>

        
        

        

        <li class="nav-item">
          <a href="/#course">
            
            <span>Course</span>
          </a>
        </li>

        
        

        

        <li class="nav-item">
          <a href="/#contact">
            
            <span>Contact</span>
          </a>
        </li>

        
        
      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  

  <div class="article-container">
    <h1 itemprop="name">March-13-2017-Pre-Class</h1>
    

<div class="article-metadata">

  <span class="article-date">
    <time datetime="2017-03-20 00:00:00 &#43;0000 UTC" itemprop="datePublished">
      Mon, Mar 20, 2017
    </time>
  </span>

  

  

  
  
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=https%3a%2f%2fzsi1.github.io%2fpost%2fmarch-13-2017-pre-class%2f"
         target="_blank">
        <i class="fa fa-facebook"></i>
      </a>
    </li>
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=March-13-2017-Pre-Class&amp;url=https%3a%2f%2fzsi1.github.io%2fpost%2fmarch-13-2017-pre-class%2f"
         target="_blank">
        <i class="fa fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=https%3a%2f%2fzsi1.github.io%2fpost%2fmarch-13-2017-pre-class%2f&amp;title=March-13-2017-Pre-Class"
         target="_blank">
        <i class="fa fa-linkedin"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=https%3a%2f%2fzsi1.github.io%2fpost%2fmarch-13-2017-pre-class%2f&amp;title=March-13-2017-Pre-Class"
         target="_blank">
        <i class="fa fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=March-13-2017-Pre-Class&amp;body=https%3a%2f%2fzsi1.github.io%2fpost%2fmarch-13-2017-pre-class%2f">
        <i class="fa fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>

    <div class="article-style" itemprop="articleBody">
      <!-- BLOGDOWN-HEAD -->
<!-- /BLOGDOWN-HEAD -->

<!-- BLOGDOWN-BODY-BEFORE -->
<!-- /BLOGDOWN-BODY-BEFORE -->
<div id="a" class="section level3">
<h3>1.a</h3>
<p>When a gambler makes a bet of $100 on a fair game, the result of this game follow bernoulli distribution with p=0.5. When we simulate the outcome at most 5000 iteration then the outcome follows a binomial distribution with n=5000, p=0.5.</p>
<pre class="r"><code>set.seed(2560)
n&lt;-5000
inital&lt;-1000
dur&lt;-rep(NA,n)
x&lt;-inital
d&lt;-0

for (j in 1:n){
  x&lt;-inital
  d&lt;-0
for (i in 1:n){
if(x!=0){
x&lt;-x+100*sample(c(-1,1),1,replace=TRUE,prob=c(0.5,0.5))
d&lt;-i
}else{break}
dur[j]&lt;-d
}}

dur&lt;-as.vector(dur)
length1a&lt;-length(which(dur&lt;=100))
prob1a&lt;-length1a/n</code></pre>
<p>The probability that get busted by the time when we have placed one hundredth bet is 31.34%.</p>
</div>
<div id="b" class="section level3">
<h3>1.b</h3>
<pre class="r"><code>length1b&lt;-length(which(dur&lt;=500))
prob1b&lt;-length1b/n
prob1b</code></pre>
<pre><code>## [1] 0.6532</code></pre>
<p>The probability that get busted by the time when we have placed one hundredth bet is 65.32%</p>
</div>
<div id="c" class="section level3">
<h3>1.c</h3>
<pre class="r"><code>dur.1c&lt;-dur[!dur==5000]
mean.time&lt;-mean(dur.1c)
mean.time</code></pre>
<pre><code>## [1] 506.204</code></pre>
<p>The mean time that go bust given go bust within the first 5000 hands is 506.204.</p>
</div>
<div id="d" class="section level3">
<h3>1.d</h3>
<pre class="r"><code>set.seed(2560)
bankroll.1d&lt;-rep(NA,n)

for (j in 1:n){
  x&lt;-inital
for (i in 1:100){
if(x!=0){
x&lt;-x+100*sample(c(-1,1),1,replace=TRUE,prob=c(0.5,0.5))
}}
bankroll.1d[j]&lt;-x
}

mean1d&lt;-mean(bankroll.1d)
var1d&lt;-var(bankroll.1d)</code></pre>
<p>The mean of bankroll after 100 hands is 989.96, and the variance of bankroll is 8.482528510^{5}.</p>
</div>
<div id="e" class="section level3">
<h3>1.e</h3>
<pre class="r"><code>set.seed(2560)
bankroll.1e&lt;-rep(NA,n)

for (j in 1:n){
  x&lt;-inital
for (i in 1:500){
if(x!=0){
x&lt;-x+100*sample(c(-1,1),1,replace=TRUE,prob=c(0.5,0.5))
}}
bankroll.1e[j]&lt;-x
}

mean1e&lt;-mean(bankroll.1e,na.rm=T)
mean1e</code></pre>
<pre><code>## [1] 1004.56</code></pre>
<pre class="r"><code>var1e&lt;-var(bankroll.1e)
var1e</code></pre>
<pre><code>## [1] 2732622</code></pre>
<p>The mean of bankroll after 500 hands is 1004.56, and the variance of bankroll after 500 hands is 2.732621710^{6}.</p>
</div>
<div id="a-1" class="section level3">
<h3>2.a</h3>
<pre class="r"><code>set.seed(2560)
p&lt;-18/38
dur2&lt;-rep(NA,n)

for (j in 1:n){
  x&lt;-inital
  d&lt;-0
for (i in 1:n){
if(x!=0){
x&lt;-x+100*sample(c(-1,1),1,replace=TRUE,prob=c(1-p,p))
d&lt;-i
}else{break()}}
dur2[j]&lt;-d
}

prob2a&lt;-length(which(dur2&lt;=100))/n
prob2a</code></pre>
<pre><code>## [1] 0.5034</code></pre>
<p>The probability that get busted by the time when we have placed one hundredth bet is 0.5034.</p>
</div>
<div id="b-1" class="section level3">
<h3>2.b</h3>
<pre class="r"><code>prob2b&lt;-length(which(dur2&lt;=500))/n</code></pre>
<p>The probability that get busted by the time when we have placed five hundredth bet is 91.9%.</p>
</div>
<div id="c-1" class="section level3">
<h3>2.c</h3>
<pre class="r"><code>dur2.c&lt;-dur2[!dur2==5000]
mean.2c&lt;-mean(dur2.c)</code></pre>
<p>The mean time that go bust given go bust within the first 5000 hands is 186.622</p>
</div>
<div id="d-1" class="section level3">
<h3>2.d</h3>
<pre class="r"><code>set.seed(2560)
bankroll.2d&lt;-rep(NA,n)

for (j in 1:n){
  x&lt;-inital
for (i in 1:100){
if(x!=0){
x&lt;-x+100*sample(c(-1,1),1,replace=TRUE,prob=c(1-p,p))
}}
bankroll.2d[j]&lt;-x
}

mean2d&lt;-mean(bankroll.2d)
var2d&lt;-var(bankroll.2d)

mean2d</code></pre>
<pre><code>## [1] 608.72</code></pre>
<pre class="r"><code>var2d</code></pre>
<pre><code>## [1] 597547.5</code></pre>
<p>The mean of bankroll after 100 hands is 608.72, and the variance of bankroll is 5.975474710^{5}.</p>
</div>
<div id="e-1" class="section level3">
<h3>2.e</h3>
<pre class="r"><code>set.seed(2560)
bankroll.2e&lt;-rep(NA,n)

for (j in 1:n){
  x&lt;-inital
for (i in 1:500){
if(x!=0){
x&lt;-x+100*sample(c(-1,1),1,replace=TRUE,prob=c(1-p,p))
}}
bankroll.2e[j]&lt;-x
}

mean2e&lt;-mean(bankroll.2e)
var2e&lt;-var(bankroll.2e)

mean2e</code></pre>
<pre><code>## [1] 167.6</code></pre>
<pre class="r"><code>var2e</code></pre>
<pre><code>## [1] 400342.3</code></pre>
<p>The mean of bankroll after 500 hands is 167.6, and the variance of bankroll is 4.003423110^{5}.</p>
</div>
<div id="a-2" class="section level3">
<h3>3.a</h3>
<pre class="r"><code>ini.win&lt;-0.48
p3&lt;-ini.win
prob3a&lt;-rep(NA,100000)
return&lt;-rep(NA,100000)
expected.return&lt;-rep(NA,100)
set.seed(2560)

for (j in 1:100){
for (i in 1:100000){
first&lt;-sample(c(-1,1),1,replace = TRUE,prob=c(1-p3,p3))
return[i+1]&lt;-return[i]+100*sample(c(-1,1),1,replace = TRUE,prob=c(1-p3,p3))
#first.return&lt;-100*first
if (p3&lt;1){
  if(first==1){
    p3&lt;-p3+0.01
  }else{p3&lt;-ini.win}
}else{p3=1}
prob3a[i]&lt;-p3
}
expected.return[j]&lt;-return[100000] 
  }
mean.3a&lt;-mean(expected.return)</code></pre>
<p>It’s not a fair game, the more hands a gambler play the more money he will lose on this game.</p>
</div>
<div id="b-2" class="section level3">
<h3>3.b</h3>
<p>Suppose the probability of winning on first hand is 51%, and the rest probabilities are the same as previous. When the starting probability is 49% the game is becoming fair.</p>
<pre class="r"><code>p4&lt;-0.51
return2&lt;-rep(NA,100000)
expected.return2&lt;-rep(NA,100)
prob3b&lt;-rep(NA,100000)

for (j in 1:100){
for (i in 1:100000){
first&lt;-sample(c(-1,1),1,replace = TRUE,prob=c(1-p4,p4))
#return2[i+1]&lt;-return2[i]+100*sample(c(-1,1),1,replace = TRUE,prob=c(1-p4,p4))
if (p4&lt;1){
  if(first==1){
    p4&lt;-p4+0.01
  }else{p4=0.51}
}else{p4=1}
prob3b[i]&lt;-p4
return2[1]&lt;-100*first
return2[i+1]&lt;-return2[i]+100*sample(c(-1,1),1,replace = TRUE,prob=c(1-p4,p4))}
expected.return2[j]&lt;-return2[100000] 
}
mean.er2&lt;-mean(expected.return2)


#try set the starting probability to 50%
p5&lt;-0.5
return3&lt;-rep(NA,100000)
expected.return3&lt;-rep(NA,100)

for (j in 1:100){
for (i in 1:100000){
first&lt;-sample(c(-1,1),1,replace = TRUE,prob=c(1-p5,p5))
#return2[i+1]&lt;-return2[i]+100*sample(c(-1,1),1,replace = TRUE,prob=c(1-p4,p4))
if (p5&lt;1){
  if(first==1){
    p5&lt;-p5+0.01
  }else{p5=0.5}
}else{p5=1}
return3[1]&lt;-100*first
return3[i+1]&lt;-return3[i]+100*sample(c(-1,1),1,replace = TRUE,prob=c(1-p5,p5))}
expected.return3[j]&lt;-return3[100000] 
}

mean.er3&lt;-mean(expected.return3)</code></pre>
<pre class="r"><code>#try set the starting probability to 49%
p6&lt;-0.49
return4&lt;-rep(NA,100000)
expected.return4&lt;-rep(NA,100)

for (j in 1:100){
for (i in 1:100000){
first&lt;-sample(c(-1,1),1,replace = TRUE,prob=c(1-p6,p6))
#return2[i+1]&lt;-return2[i]+100*sample(c(-1,1),1,replace = TRUE,prob=c(1-p4,p4))
if (p6&lt;1){
  if(first==1){
    p6&lt;-p6+0.01
  }else{p6=0.49}
}else{p6=1}
return4[1]&lt;-100*first
return4[i+1]&lt;-return4[i]+100*sample(c(-1,1),1,replace = TRUE,prob=c(1-p6,p6))}
expected.return4[j]&lt;-return4[100000] 
}

mean.er4&lt;-mean(expected.return4)
mean.er4</code></pre>
<pre><code>## [1] 16474</code></pre>
</div>
<div id="c-2" class="section level3">
<h3>3.c</h3>
<p>When set the increment probability at 2%, this game is becoming a fair game.</p>
<pre class="r"><code>#set the increment probability to 1.5%
set.seed(2560)
p3&lt;-0.48
return5&lt;-rep(NA,100000)
expected.return5&lt;-rep(NA,100)

for (j in 1:100){
for (i in 1:100000){
first&lt;-sample(c(-1,1),1,replace = TRUE,prob=c(1-p3,p3))
if (p3&lt;0.985){
  if(first==1){
    p3&lt;-p3+0.015
  }else{p3&lt;-0.48}
}else{p3==1}
return5[1]&lt;-100*first
return5[i+1]&lt;-return5[i]+100*sample(c(-1,1),1,replace = TRUE,prob=c(1-p3,p3))}
expected.return5[j]&lt;-return5[100000] 
}
mean(expected.return5)</code></pre>
<pre><code>## [1] 9726258</code></pre>
<pre class="r"><code>#set the increment probability to 2%
p3&lt;-0.48
return6&lt;-rep(NA,100000)
expected.return6&lt;-rep(NA,100)
set.seed(2560)

for (j in 1:100){
for (i in 1:100000){
first&lt;-sample(c(-1,1),1,replace = TRUE,prob=c(1-p3,p3))
if (p3&lt;0.98){
  if(first==1){
    p3&lt;-p3+0.02
  }else{p3&lt;-0.48}
}else{p3==1}
return6[1]&lt;-100*first
return6[i+1]&lt;-return6[i]+100*sample(c(-1,1),1,replace = TRUE,prob=c(1-p3,p3))}
expected.return6[j]&lt;-return6[100000] 
}

mean(expected.return6)</code></pre>
<pre><code>## [1] 9591612</code></pre>
<pre class="r"><code>#set the increment probability to 1.55%

p3&lt;-0.48
return7&lt;-rep(NA,100000)
expected.return7&lt;-rep(NA,100)
set.seed(2560)

for (j in 1:100){
for (i in 1:100000){
first&lt;-sample(c(-1,1),1,replace = TRUE,prob=c(1-p3,p3))
if (first==1){
  if(p3&lt;0.9845){
    p3&lt;-p3+0.0155
  } else {p3=1}
}else{p3=0.48}
 return7[1]&lt;-100*first
 return7[i+1]&lt;-return7[i]+100*sample(c(-1,1),1,replace = TRUE,prob=c(1-p3,p3))}
  expected.return7[j]&lt;-return7[100000]
  }
mean(expected.return7)</code></pre>
<pre><code>## [1] 9924696</code></pre>
</div>
<div id="section" class="section level3">
<h3>4</h3>
<pre class="r"><code>set.seed(2560)
B&lt;-1000
d1&lt;-as.matrix(expected.return4)
d1&lt;-data.frame(d1)
mean1&lt;-rep(NA,100)
for (i in 1:B){
  n&lt;-nrow(d1)
  index1&lt;-sample(1:n,size=n,replace=TRUE)
  boot.data1&lt;-d1[index1,]
  mean1[i]&lt;-mean(boot.data1)
  }
var4.1&lt;-var(mean1)


set.seed(2560)
d2&lt;-as.matrix(expected.return6)
d2&lt;-data.frame(d2)
mean2&lt;-rep(NA,100)
for (i in 1:B){
  n&lt;-nrow(d2)
  index2&lt;-sample(1:n,size=n,replace=TRUE)
  boot.data2&lt;-d2[index2,]
  mean2[i]&lt;-mean(boot.data2)
}
var4.2&lt;-var(mean2)</code></pre>
<p>The variance of second game mean of return is 2614 and the variance of first game mean of return is 10228630. In general, the second game has a smaller variance in returns.</p>
</div>

    </div>
  </div>

</article>

<div class="container">
  <nav>
  <ul class="pager">
    
    <li class="previous"><a href="https://zsi1.github.io/post/feb-28-2016-in-class-project/"><span
      aria-hidden="true">&larr;</span> Feb, 28, 2016 -In-Class Project</a></li>
    

    
    <li class="next"><a href="https://zsi1.github.io/post/march-07-2017-in-class/">March-07-2017-In-Class <span
      aria-hidden="true">&rarr;</span></a></li>
    
  </ul>
</nav>

</div>

<div class="article-container">
  
<section id="comments">
  <div id="disqus_thread">
    <div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'https-zsi1-github-io';
    var disqus_identifier = 'https:\/\/zsi1.github.io\/post\/march-13-2017-pre-class\/';
    var disqus_title = 'March-13-2017-Pre-Class';
    var disqus_url = 'https:\/\/zsi1.github.io\/post\/march-13-2017-pre-class\/';

    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
  </div>
</section>


</div>

<footer class="site-footer">
  <div class="container">
    <p class="powered-by">

      &copy; 2016 Your Name &middot; 

      Powered by the <a href="https://github.com/gcushen/hugo-academic" target="_blank">Academic
      theme</a> for <a href="http://gohugo.io" target="_blank">Hugo</a>.

      <span class="pull-right" aria-hidden="true">
        <a href="#" id="back_to_top">
          <span class="button_icon">
            <i class="fa fa-chevron-up fa-2x"></i>
          </span>
        </a>
      </span>

    </p>
  </div>
</footer>

    <script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.4/TweenMax.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/gsap/latest/plugins/ScrollToPlugin.min.js"></script>
    <script src="/js/jquery-1.12.3.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/isotope.pkgd.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.1/imagesloaded.pkgd.min.js"></script>
    <script src="/js/hugo-academic.js"></script>
    

    

    
    
      
      <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js"></script>

      

      

      <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });
    </script>
    <script async src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML"></script>
    

  </body>
</html>

